[mod] Basic install/remove scripts.

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -24,24 +24,9 @@ ynh_abort_if_errors
 # RETRIEVE ARGUMENTS FROM THE MANIFEST
 #=================================================
 
-domain=$YNH_APP_ARG_DOMAIN
-path_url=$YNH_APP_ARG_PATH
-admin=$YNH_APP_ARG_ADMIN
-is_public=$YNH_APP_ARG_IS_PUBLIC
-language=$YNH_APP_ARG_LANGUAGE
-password=$YNH_APP_ARG_PASSWORD
-
-### If it's a multi-instance app, meaning it can be installed several times independently
-### The id of the app as stated in the manifest is available as $YNH_APP_ID
-### The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
-### The app instance name is available as $YNH_APP_INSTANCE_NAME
-###    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
-###    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
-###    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
-### The app instance name is probably what interests you most, since this is
-### guaranteed to be unique. This is a good unique identifier to define installation path,
-### db names, ...
 app=$YNH_APP_INSTANCE_NAME
+domain=$YNH_APP_ARG_DOMAIN
+admin=$YNH_APP_ARG_ADMIN
 
 #=================================================
 # CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
@@ -49,26 +34,14 @@ app=$YNH_APP_INSTANCE_NAME
 
 ### If the app uses nginx as web server (written in HTML/PHP in most cases), the final path should be "/var/www/$app".
 ### If the app provides an internal web server (or uses another application server such as uwsgi), the final path should be "/opt/yunohost/$app"
-final_path=/var/www/$app
-test ! -e "$final_path" || ynh_die "This path already contains a folder"
-
-# Normalize the url path syntax
-path_url=$(ynh_normalize_url_path $path_url)
-
-# Check web path availability
-ynh_webpath_available $domain $path_url
-# Register (book) web path
-ynh_webpath_register $app $domain $path_url
+#final_path=/var/lib/biboumi
+#test ! -e "$final_path" || ynh_die "This path already contains a folder"
 
 #=================================================
 # STORE SETTINGS FROM MANIFEST
 #=================================================
 
-ynh_app_setting_set $app domain $domain
-ynh_app_setting_set $app path $path_url
-ynh_app_setting_set $app admin $admin
-ynh_app_setting_set $app is_public $is_public
-ynh_app_setting_set $app language $language
+# Nothing special here.
 
 #=================================================
 # STANDARD MODIFICATIONS
@@ -81,11 +54,11 @@ ynh_app_setting_set $app language $language
 ### If you're not using these lines:
 ###		- Remove the section "CLOSE A PORT" in the remove script
 
-# Find a free port
-port=$(ynh_find_port 8095)
-# Open this port
-yunohost firewall allow --no-upnp TCP $port 2>&1
-ynh_app_setting_set $app port $port
+## Find a free port
+#port=$(ynh_find_port 8095)
+## Open this port
+#yunohost firewall allow --no-upnp TCP $port 2>&1
+#ynh_app_setting_set $app port $port
 
 #=================================================
 # INSTALL DEPENDENCIES
@@ -98,70 +71,14 @@ ynh_app_setting_set $app port $port
 ###		- As well as the section "REINSTALL DEPENDENCIES" in the restore script
 ###		- And the section "UPGRADE DEPENDENCIES" in the upgrade script
 
-ynh_install_app_dependencies deb1 deb2
+# Make sure that stretch-backports is enabled
+if ! apt-cache policy | grep 'stretch-backports/main'
+then
+	echo "deb http://ftp.fr.debian.org/debian/ stretch-backports main" | sudo tee /etc/apt/sources.list.d/${app}_needs_stretch-backports.list
+	echo "Adding stretch-backports repository..."
+fi
 
-#=================================================
-# CREATE A MYSQL DATABASE
-#=================================================
-
-### Use these lines if you need a database for the application.
-### `ynh_mysql_setup_db` will create a database, an associated user and a ramdom password.
-### The password will be stored as 'mysqlpwd' into the app settings,
-### and will be available as $db_pwd
-### If you're not using these lines:
-###		- Remove the section "BACKUP THE MYSQL DATABASE" in the backup script
-###		- Remove also the section "REMOVE THE MYSQL DATABASE" in the remove script
-###		- As well as the section "RESTORE THE MYSQL DATABASE" in the restore script
-
-db_name=$(ynh_sanitize_dbid $app)
-ynh_app_setting_set $app db_name $db_name
-ynh_mysql_setup_db $db_name $db_name
-
-#=================================================
-# DOWNLOAD, CHECK AND UNPACK SOURCE
-#=================================================
-
-### `ynh_setup_source` is used to install an app from a zip or tar.gz file,
-### downloaded from an upstream source, like a git repository.
-### `ynh_setup_source` use the file conf/app.src
-
-ynh_app_setting_set $app final_path $final_path
-# Download, check integrity, uncompress and patch the source from app.src
-ynh_setup_source "$final_path"
-
-#=================================================
-# NGINX CONFIGURATION
-#=================================================
-
-### `ynh_add_nginx_config` will use the file conf/nginx.conf
-
-# Create a dedicated nginx config
-ynh_add_nginx_config
-
-#=================================================
-# CREATE DEDICATED USER
-#=================================================
-
-# Create a system user
-ynh_system_user_create $app
-
-#=================================================
-# PHP-FPM CONFIGURATION
-#=================================================
-
-### `ynh_add_fpm_config` is used to set up a PHP config.
-### You can remove it if your app doesn't use PHP.
-### `ynh_add_fpm_config` will use the files conf/php-fpm.conf and conf/php-fpm.ini
-### If you're not using these lines:
-###		- You can remove these files in conf/.
-###		- Remove the section "BACKUP THE PHP-FPM CONFIGURATION" in the backup script
-###		- Remove also the section "REMOVE PHP-FPM CONFIGURATION" in the remove script
-###		- As well as the section "RESTORE THE PHP-FPM CONFIGURATION" in the restore script
-###		With the reload at the end of the script.
-###		- And the section "PHP-FPM CONFIGURATION" in the upgrade script
-
-# Create a dedicated php-fpm config
-ynh_add_fpm_config
+ynh_install_app_dependencies biboumi
 
 #=================================================
 # SPECIFIC SETUP
@@ -169,61 +86,41 @@ ynh_add_fpm_config
 # ...
 #=================================================
 
-#=================================================
-# SETUP SYSTEMD
-#=================================================
+# Create a secret password that will be shared by metronome and biboumi.
+shared_secret="$(ynh_string_random 25)"
 
-### `ynh_systemd_config` is used to configure a systemd script for an app.
-### It can be used for apps that use sysvinit (with adaptation) or systemd.
-### Have a look at the app to be sure this app needs a systemd script.
-### `ynh_systemd_config` will use the file conf/systemd.service
-### If you're not using these lines:
-###		- You can remove those files in conf/.
-###		- Remove the section "BACKUP SYSTEMD" in the backup script
-###		- Remove also the section "STOP AND REMOVE SERVICE" in the remove script
-###		- As well as the section "RESTORE SYSTEMD" in the restore script
-###		- And the section "SETUP SYSTEMD" in the upgrade script
+# Biboumi needs at least one admin JID.
+admin_jid="${admin}@biboumi.${domain}"
 
-# Create a dedicated systemd config
-ynh_add_systemd_config
+# Create the biboumi config file.
+cp ../conf/biboumi.cfg /etc/biboumi/
+ynh_replace_string __DOMAIN__ "${domain}" /etc/biboumi/biboumi.cfg
+ynh_replace_string __SECRET__ "${shared_secret}" /etc/biboumi/biboumi.cfg
+ynh_replace_string __ADMIN_JID__ "${admin_jid}" /etc/biboumi/biboumi.cfg
 
-#=================================================
-# SETUP APPLICATION WITH CURL
-#=================================================
+MARKER_START="-- START Patch from biboumi_ynh"
+MARKER_END="-- END Patch from biboumi_ynh"
 
-### Use these lines only if the app installation needs to be finalized through
-### web forms. We generally don't want to ask the final user,
-### so we're going to use curl to automatically fill the fields and submit the
-### forms.
+# Patch metronome's main config file.
+metronome_component="\
+${MARKER_START}\\n\
+Component \"biboumi.${domain}\"\\n\
+    component_secret = \"${shared_secret}\"\\n\
+${MARKER_END}\\n"
 
-# Set right permissions for curl install
-chown -R $app: $final_path
-
-# Set the app as temporarily public for curl call
-ynh_app_setting_set $app skipped_uris "/"
-# Reload SSOwat config
-yunohost app ssowatconf
-
-# Reload Nginx
-systemctl reload nginx
-
-# Installation with curl
-ynh_local_curl "/INSTALL_PATH" "key1=value1" "key2=value2" "key3=value3"
-
-# Remove the public access
-if [ $is_public -eq 0 ]
+# Try to detect if metronome's main config file was not patched yet.
+if grep -q -- "${MARKER_START}" /etc/metronome/metronome.cfg.lua
 then
-	ynh_app_setting_delete $app skipped_uris
+	echo "Metronome's configuration file is already patched. This is unexpected. Cowardly aborting installation..."
+	ynh_die 42
 fi
 
-#=================================================
-# MODIFY A CONFIG FILE
-#=================================================
+#sed -i "s/----------- Virtual hosts/${metronome_component}----------- Virtual hosts/" /etc/metronome/metronome.cfg.lua
+ynh_replace_string "^----------- Virtual hosts" "${metronome_component}&" /etc/metronome/metronome.cfg.lua
 
-### `ynh_replace_string` is used to replace a string in a file.
-### (It's compatible with sed regular expressions syntax)
 
-ynh_replace_string "match_string" "replace_string" "$final_path/CONFIG_FILE"
+mkdir -p /var/log/biboumi /var/lib/biboumi
+chown _biboumi /var/log/biboumi /var/lib/biboumi
 
 #=================================================
 # STORE THE CONFIG FILE CHECKSUM
@@ -234,20 +131,7 @@ ynh_replace_string "match_string" "replace_string" "$final_path/CONFIG_FILE"
 ### you can make a backup of this file before modifying it again if the admin had modified it.
 
 # Calculate and store the config file checksum into the app settings
-ynh_store_file_checksum "$final_path/CONFIG_FILE"
-
-#=================================================
-# GENERIC FINALIZATION
-#=================================================
-# SECURE FILES AND DIRECTORIES
-#=================================================
-
-### For security reason, any app should set the permissions to root: before anything else.
-### Then, if write authorization is needed, any access should be given only to directories
-### that really need such authorization.
-
-# Set permissions to app files
-chown -R root: $final_path
+#ynh_store_file_checksum "$final_path/CONFIG_FILE"
 
 #=================================================
 # SETUP LOGROTATE
@@ -262,7 +146,8 @@ chown -R root: $final_path
 ###		- And the section "SETUP LOGROTATE" in the upgrade script
 
 # Use logrotate to manage application logfile(s)
-ynh_use_logrotate
+#ynh_use_logrotate
+# TODO setup logrotate
 
 #=================================================
 # ADVERTISE SERVICE IN ADMIN PANEL
@@ -276,21 +161,15 @@ ynh_use_logrotate
 ###		- Remove the section "REMOVE SERVICE FROM ADMIN PANEL" in the remove script
 ###		- As well as the section ADVERTISE SERVICE IN ADMIN PANEL" in the restore script
 
-yunohost service add NAME_INIT.D --log "/var/log/FILE.log"
+yunohost service add biboumi
+
+# TODO Try to make "yunohost service" able to display logs from journalctl
+# yunohost service add biboumi --log "/var/log/FILE.log"
+
 
 #=================================================
-# SETUP SSOWAT
+# RELOAD SERVICES
 #=================================================
 
-# Make app public if necessary
-if [ $is_public -eq 1 ]
-then
-	# unprotected_uris allows SSO credentials to be passed anyway.
-	ynh_app_setting_set $app unprotected_uris "/"
-fi
-
-#=================================================
-# RELOAD NGINX
-#=================================================
-
-systemctl reload nginx
+ynh_systemd_action -a restart -n metronome
+ynh_systemd_action -a restart -n biboumi -p /var/log/biboumi/biboumi.log
